---
- name: Include distribution-specific tasks
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution }}.yml"

- name: Install Docker packages
  ansible.builtin.package:
    name:
      - docker-ce
    state: present

- name: Create the Docker volume base directory
  ansible.builtin.file:
    path: "{{ docker_data_dir }}"
    mode: u=rwx,g=rx,o=rx
    state: directory
    follow: false

- name: Ensure the docker config directory exists
  ansible.builtin.file:
    path: /etc/docker/
    mode: u=rwx,g=rx,o=rx
    state: directory
    follow: false

- name: Configure dockerd
  ansible.builtin.copy:
    # language=json
    content: |
      {
        "data-root": "{{ docker_data_dir }}",
        "default-address-pools" : {{ address_pools | to_json }}
      }
    dest: /etc/docker/daemon.json
    mode: u=rw,g=r,o=r
  register: dockerd_config

- name: Enable the Docker daemon
  ansible.builtin.service:
    name: docker
    enabled: true

- name: Start the Docker daemon
  ansible.builtin.service:
    name: docker
    state: started
  register: dockerd_started

- name: Restart the Docker daemon
  ansible.builtin.service:
    name: docker
    state: restarted
  when: dockerd_config is changed and dockerd_started is not changed
