---
- name: Provision an OpenStack VM by calling Terraform from Ansible
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Test creation of an execution plan for Terraform
      cloud.terraform.terraform:
        project_path: "{{ tf_project_path }}"
        state: present
        force_init: true
        variables:
          vm_name: "{{ vm_name }}"
          vm_image_name: "{{ vm_image_name }}"
          vm_flavor_name: "{{ vm_flavor_name }}"
          vm_key_pair: "{{ vm_key_pair }}"
          vm_security_group: "{{ vm_security_group }}"
          vm_network: "{{ vm_network }}"
          vm_ssh_key_file: "{{ vm_ssh_key_file }}"
          vm_ssh_user: "{{ vm_ssh_user }}"
      no_log: true
      check_mode: true

    - name: Create and execute Terraform plan
      cloud.terraform.terraform:
        project_path: "{{ tf_project_path }}"
        state: present
        variables:
          vm_name: "{{ vm_name }}"
          vm_image_name: "{{ vm_image_name }}"
          vm_flavor_name: "{{ vm_flavor_name }}"
          vm_key_pair: "{{ vm_key_pair }}"
          vm_security_group: "{{ vm_security_group }}"
          vm_network: "{{ vm_network }}"
          vm_ssh_key_file: "{{ vm_ssh_key_file }}"
          vm_ssh_user: "{{ vm_ssh_user }}"
      no_log: true
      register: terraform_result
      check_mode: false

    - name: Assert that Terraform output value is defined
      ansible.builtin.assert:
        that:
          - terraform_result.outputs.vm_ip_address.value is defined

  post_tasks:
    - name: Create in-memory inventory for the VM
      ansible.builtin.add_host:
        name: vm
        groups: vms
        ansible_host: "{{ terraform_result.outputs.vm_ip_address.value }}"
        ansible_user: "{{ vm_ssh_user }}"
        ansible_ssh_private_key_file: "{{ vm_ssh_key_file }}"
        ansible_ssh_common_args: >
          -o IdentitiesOnly=yes
          -o BatchMode=yes
          -o UserKnownHostsFile=/dev/null
          -o StrictHostKeyChecking=no

- name: Configure an OpenStack VM using Ansible
  hosts: vms
  gather_facts: false
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Waits until remote VM is usable
      ansible.builtin.wait_for_connection:
        delay: 10
        sleep: 5
        timeout: 120
  tasks:
    - name: A configuration block for the web server
      become: true
      block:
        - name: Install Apache
          ansible.builtin.apt:
            package: apache2
            state: present
            update_cache: true

        - name: Start Apache service
          ansible.builtin.service:
            name: apache2
            state: started

        - name: Copy website files
          ansible.builtin.copy:
            src: html/index.html
            dest: /var/www/html/index.html
            mode: 0644
          notify: Restart Apache service
  handlers:
    - name: Restart Apache service
      ansible.builtin.service:
        name: apache2
        state: restarted
      become: true
