---
- name: Prepare and send reports to Ninja masters
  hosts: localhost
  vars:
    ninjas: "{{ lookup('file','data.json') | from_json }}"
    datetime: "{{ ansible_date_time.iso8601 }}"
  tasks:
    - name: Print datetime and initial data
      ansible.builtin.debug:
        msg:
          - "{{ datetime }}"
          - "{{ ninjas }}"

    - name: Create global directory for reports
      ansible.builtin.file:
        state: directory
        path: "{{ datetime }}"
        mode: "0777"

    - name: Prepare reports for all masters
      ansible.builtin.set_fact:
        grandninja_lotus_report: |
          <table>
            <tr>
              <th>Name</th>
              <th>Age</th>
              <th>Color</th>
              <th>Location</th>
              <th>Status</th>
            </tr>
            {% for ninja in ninjas %}
              <tr>
                <td>{{ ninja['name'] }}</td>
                <td>{{ ninja['age'] }}</td>
                <td>{{ ninja['color'] }}</td>
                <td>{{ ninja['location'] }}</td>
                <td>{{ ninja['status'] }}</td>
              </tr>
            {% endfor %}
          </table>
        sensei_shadowstrike_report: |
          {% set filtered_ninjas = ninjas | selectattr('age', '>', 18) | selectattr('location', 'equalto', 'Ninjatropolis') %}
          Name,Age,Color,Location,Status
          {% for ninja in filtered_ninjas %}
          {{ ninja.name }},{{ ninja.age }},{{ ninja.color }},{{ ninja.location }},{{ ninja.status }}
          {% endfor %}
        hanzo_katanzo_report: "{{ (ninjas | last).name | lower }}"
        jokemaster_noodle_nunchuck_report: |
          groups:
          {% for color, color_group in ninjas | groupby('color') %}
            {{ color }}:
              count: {{ color_group | length }}
              min_age: {{ color_group | map(attribute='age') | min }}
              max_age: {{ color_group | map(attribute='age') | max }}
              average_age: {{ color_group | map(attribute='age') | sum / color_group | length | round(2) }}
              subgroups:
          {%    for status, status_group in color_group | groupby('status') %}
                {{ status }}:
                  count: {{ status_group | length }}
                  ninjas:
          {%        for ninja in status_group %}
                    - "{{ ninja.name }}"
          {%        endfor %}
          {%    endfor %}
          {% endfor %}
        chuck_norrisuki_report: |
          {%- macro factorial(n, return_value=1) -%}
            {%- if n > 1 -%}
              {%- set return_value = n * return_value -%}
              {{- factorial(n-1,return_value) -}}
            {%- else -%}
              {{ return_value }}
            {%- endif -%}
          {%- endmacro -%}

          {% for ninja in ninjas %}
          {%   if ninja.age is odd %}
          {{     ninja.name.split()[0] | upper | reverse }}: {{ factorial(ninja.age) }}
          {%   endif %}
          {% endfor %}

    - name: Save reports for Ninja masters
      ansible.builtin.copy:
        content: "{{ item.report_content }}"
        dest: "{{ datetime }}/{{ item.report_name }}"
        mode: "0644"
      loop:
        - report_content: "{{ grandninja_lotus_report }}"
          report_name: "grandninja_lotus_report.html"
        - report_content: "{{ sensei_shadowstrike_report }}"
          report_name: "sensei_shadowstrike_report.csv"
        - report_content: "{{ hanzo_katanzo_report }}"
          report_name: "hanzo_katanzo_report.txt"
        - report_content: "{{ jokemaster_noodle_nunchuck_report }}"
          report_name: "jokemaster_noodle_nunchuck_report.yml"
        - report_content: "{{ chuck_norrisuki_report }}"
          report_name: "chuck_norrisuki_report.txt"

    - name: Send reports to Ninja masters
      check_mode: true
      no_log: true
      ignore_errors: true
      block:
        - name: Send an e-mail to Grandninja Lotus using Gmail SMTP servers
          community.general.mail:
            host: smtp.gmail.com
            port: 587
            username: !unsafe "ninjas@example.com"
            password: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              64326565646435333534653564653036313330383835616265396530393534393536313538323264
              6265303235653865386230663031623738336335353138640a303732373938633038393965653662
              34643365613836646130646461616366633861363462613938356565396130613038373736643437
              3132336262323966390a306438656436326363623839376339643962333830343730623530643231
            to: Grandninja Lotus <grandninja.lotus@example.com>
            subject: Ansible-Ninja-Status-Weekly-Report
            body: "{{ grandninja_lotus_report }}"

        - name: Upload a CSV report to Azure Container for Sensei Shadowstrike
          azure.azcollection.azure_rm_storageblob:
            resource_group: LotusResourceGroup
            storage_account_name: LotusStorageAccount
            container: ninjas
            blob: "{{ datetime }}.csv"
            src: "{{ datetime }}/sensei_shadowstrike_report.csv"
            content_type: "text/csv"

        - name: Publish a report to RabbitMQ queue for Hanzo Katanzo
          community.rabbitmq.rabbitmq_publish:
            exchange: ninjas
            url: "amqp://h:k@192.168.0.32:5672/%2F"
            body: "{{ hanzo_katanzo_report }}"
            content_type: "text/plain"

        - name: Upload a YAML report to Google Storage Bucket for Jokemaster Noodle Nunchuck
          google.cloud.gcp_storage_object:
            action: upload
            bucket: ninjas
            src: "{{ datetime }}/jokemaster_noodle_nunchuck_report.yml"
            dest: "{{ datetime }}.yml"
            project: jokemaster_project
            auth_kind: serviceaccount

        - name: Upload a text report to AWS S3 Bucket for Chuck Norrisuki
          amazon.aws.s3_object:
            bucket: ninjas
            src: "{{ datetime }}/chuck_norrisuki_report.txt"
            object: "{{ datetime }}.txt"
            mode: put
